"""Public platform contracts used by the application assembly."""

from .config import RuntimePaths, app_data_dir, environment_flag, get_setting, set_setting
from .db import connect, control_db, table_exists
from .auth import (
    password_matches,
    read_token_piece,
    require_user,
    run_events_token,
    signed_scope_token,
    signed_token,
    token_piece,
    token_user,
    valid_run_events_token,
    valid_scope_token,
)
from .maintenance import MAINTENANCE_CAPABILITIES, capability_snapshot
from .app import build_lifespan, install_security_headers, lifecycle_context, mount_static_assets
from .http import LoginPayload, build_router
from .migrations import MigrationDriftError, MigrationRegistry, run_migrations
from .audit import write_event_in_connection
from .bootstrap import BootstrapResult, ControllerBootstrapService, SchemaIntrospection, apply_controller_schema_upgrades, bootstrap_controller_schema, complete_controller_bootstrap, ensure_migration_ledger, ensure_runtime_directories, run_registered_migrations
from .runs import (
    RunContext,
    RunDescriptor,
    RunEvent,
    RunEventType,
    RunState,
    RunWriter,
    append_event,
    any_active_ids_in_connection,
    append_log_in_connection,
    complete_run,
    context_and_log_in_connection,
    create_run,
    create_run_in_connection,
    start_run_in_connection,
    recent_runs,
    rename_target_in_connection,
    set_running_command_in_connection,
    status_in_connection,
    statuses_in_connection,
    stream_run_events,
    transition_run,
    transition_run_in_connection,
    update_run_status_in_connection,
    mark_recovery_required_in_connection,
    recovery_required_ids_in_connection,
    has_active_target_in_connection,
)
from .security import (
    digest,
    open_config,
    open_secret,
    redact,
    redact_config,
    seal_config,
    seal_secret,
    valid_password,
)
from .command_runs import RunLifecycleService, execute_logged_command, run_commands
from .integration import PlatformRunOperations

__all__ = [
    "RuntimePaths",
    "app_data_dir",
    "connect",
    "control_db",
    "table_exists",
    "digest",
    "environment_flag",
    "get_setting",
    "set_setting",
    "open_config",
    "open_secret",
    "redact",
    "redact_config",
    "seal_config",
    "seal_secret",
    "valid_password",
    "require_user",
    "password_matches",
    "token_user",
    "token_piece",
    "read_token_piece",
    "signed_token",
    "run_events_token",
    "valid_run_events_token",
    "signed_scope_token",
    "valid_scope_token",
    "MAINTENANCE_CAPABILITIES",
    "capability_snapshot",
    "lifecycle_context",
    "build_lifespan",
    "install_security_headers",
    "mount_static_assets",
    "build_router",
    "LoginPayload",
    "run_migrations",
    "MigrationRegistry",
    "MigrationDriftError",
    "write_event_in_connection",
    "BootstrapResult",
    "ControllerBootstrapService",
    "SchemaIntrospection",
    "apply_controller_schema_upgrades",
    "bootstrap_controller_schema",
    "complete_controller_bootstrap",
    "ensure_migration_ledger",
    "ensure_runtime_directories",
    "run_registered_migrations",
    "RunContext",
    "RunDescriptor",
    "RunEvent",
    "RunEventType",
    "RunState",
    "RunWriter",
    "append_event",
    "any_active_ids_in_connection",
    "append_log_in_connection",
    "complete_run",
    "context_and_log_in_connection",
    "create_run",
    "create_run_in_connection",
    "start_run_in_connection",
    "recent_runs",
    "rename_target_in_connection",
    "set_running_command_in_connection",
    "status_in_connection",
    "statuses_in_connection",
    "stream_run_events",
    "transition_run",
    "transition_run_in_connection",
    "update_run_status_in_connection",
    "mark_recovery_required_in_connection",
    "recovery_required_ids_in_connection",
    "has_active_target_in_connection",
    "execute_logged_command",
    "run_commands",
    "RunLifecycleService",
    "PlatformRunOperations",
]
