import { useEffect, useState } from 'react';
import {
  EuiBadge, EuiButton, EuiButtonEmpty, EuiCallOut, EuiCodeBlock, EuiFieldPassword,
  EuiFormRow, EuiModal, EuiModalBody, EuiModalFooter, EuiModalHeader, EuiModalHeaderTitle, EuiSelect,
  EuiOverlayMask, EuiSpacer, EuiText, EuiTextArea, EuiTitle,
} from '@elastic/eui';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { advancedApi } from '../api';
import { copyText } from '../../../shared/clipboard';
import { formatDateTime } from '../../../shared/format';
import type { ControllerSettings, ControllerSshKeyStatus } from '../types';

type KeyAction = 'generate' | 'import' | 'activate';

const timezoneOptions = [
  ['UTC', 'UTC'], ['Pacific/Honolulu', 'Honolulu (UTC-10)'], ['America/Los_Angeles', 'Los Angeles'],
  ['America/Denver', 'Denver'], ['America/Chicago', 'Chicago'], ['America/New_York', 'New York'],
  ['America/Sao_Paulo', 'Sao Paulo'], ['Europe/London', 'London'], ['Europe/Paris', 'Paris'],
  ['Europe/Berlin', 'Berlin'], ['Africa/Johannesburg', 'Johannesburg'], ['Asia/Dubai', 'Dubai'],
  ['Asia/Kolkata', 'Kolkata'], ['Asia/Bangkok', 'Bangkok'], ['Asia/Singapore', 'Singapore'],
  ['Asia/Hong_Kong', 'Hong Kong'], ['Asia/Shanghai', 'Shanghai'], ['Asia/Tokyo', 'Tokyo'],
  ['Asia/Seoul', 'Seoul'], ['Australia/Sydney', 'Sydney'], ['Pacific/Auckland', 'Auckland'],
].map(([value, text]) => ({ value, text }));

function sourceLabel(source: string) {
  if (source === 'legacy_mounted') return 'Legacy mounted key';
  return source === 'generated' ? 'Generated by ELKeeper' : 'Imported into ELKeeper';
}

export function ControllerIdentityPanel() {
  const client = useQueryClient();
  const { data, isLoading } = useQuery({ queryKey: ['controller-ssh-key'], queryFn: () => advancedApi.controllerKey() as Promise<ControllerSshKeyStatus> });
  const { data: settings } = useQuery({ queryKey: ['controller-settings'], queryFn: advancedApi.controllerSettings });
  const [action, setAction] = useState<KeyAction>();
  const [adminPassword, setAdminPassword] = useState('');
  const [privateKey, setPrivateKey] = useState('');
  const [passphrase, setPassphrase] = useState('');
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState('');
  const [timezone, setTimezone] = useState('Asia/Hong_Kong');
  const [timezoneBusy, setTimezoneBusy] = useState(false);
  const [timezoneError, setTimezoneError] = useState('');
  useEffect(() => { if (settings?.timezone) setTimezone(settings.timezone); }, [settings?.timezone]);
  const close = () => { setAction(undefined); setAdminPassword(''); setPrivateKey(''); setPassphrase(''); setError(''); };
  const copyPublicKey = async (value: string) => {
    try { await copyText(value); setError(''); }
    catch (reason) { setError(reason instanceof Error ? reason.message : 'Clipboard access was unavailable.'); }
  };
  const submit = async () => {
    if (!action || !adminPassword || (action === 'import' && !privateKey)) return;
    setBusy(true); setError('');
    try {
      const payload = action === 'import' ? { password: adminPassword, private_key: privateKey, passphrase: passphrase || undefined } : { password: adminPassword };
      await advancedApi.controllerKeyAction(action, payload);
      await client.invalidateQueries({ queryKey: ['controller-ssh-key'] });
      close();
    } catch (reason) { setError(reason instanceof Error ? reason.message : 'Controller key operation failed'); }
    finally { setBusy(false); }
  };
  const saveTimezone = async () => {
    setTimezoneBusy(true); setTimezoneError('');
    try {
      await advancedApi.updateControllerSettings(timezone);
      await client.invalidateQueries({ queryKey: ['controller-settings'] });
    } catch (reason) { setTimezoneError(reason instanceof Error ? reason.message : 'Unable to save display timezone'); }
    finally { setTimezoneBusy(false); }
  };
  const active = data?.active;
  return <div className="controller-tab">
    <div className="section-heading"><div><EuiTitle size="s"><h2>Controller SSH identity</h2></EuiTitle><EuiText color="subdued">A controller-owned key is used for Ansible, host probes, Podman forwarding, and telemetry.</EuiText></div></div>
    {error && !action && <EuiCallOut title="Controller key operation failed" color="danger" iconType="warning">{error}</EuiCallOut>}
    <section className="section-band">
      {isLoading && <EuiText color="subdued">Loading controller identity...</EuiText>}
      {active && <div className="controller-key-summary">
        <div><strong>Current key ID</strong><small>{active.key_id || 'Fingerprint unavailable for the mounted legacy key'}</small></div>
        <div><strong>Type</strong><small>{active.algorithm}</small></div>
        <div><strong>Source</strong><small>{sourceLabel(active.source)}</small></div>
        <div><strong>Created</strong><small>{active.created_at ? formatDateTime(active.created_at, settings?.timezone || timezone) : 'Mounted legacy key'}</small></div>
        <EuiBadge color={active.source === 'legacy_mounted' ? 'warning' : 'success'}>{active.state === 'legacy' ? 'migration fallback' : 'active'}</EuiBadge>
      </div>}
      {active?.public_key && <><EuiSpacer size="s" /><EuiCodeBlock language="text" paddingSize="s" isCopyable={false}>{active.public_key}</EuiCodeBlock><EuiSpacer size="s" /><EuiButtonEmpty iconType="copyClipboard" onClick={() => copyPublicKey(active.public_key)}>Copy public key</EuiButtonEmpty></>}
      <EuiSpacer />
      <div className="form-actions">
        <EuiButton iconType="key" onClick={() => setAction('generate')}>Generate key</EuiButton>
        <EuiButton iconType="importAction" onClick={() => setAction('import')}>Import key</EuiButton>
      </div>
    </section>
    <section className="section-band">
      <div className="section-heading"><div><EuiTitle size="s"><h2>Display timezone</h2></EuiTitle><EuiText color="subdued">Applies to dashboard timestamps, charts, certificates, and controller metadata. Stored timestamps remain in UTC.</EuiText></div></div>
      {timezoneError && <EuiCallOut title="Timezone update failed" color="danger" iconType="warning">{timezoneError}</EuiCallOut>}
      <EuiFormRow label="Timezone"><EuiSelect options={timezoneOptions} value={timezone} onChange={(event) => setTimezone(event.target.value)} /></EuiFormRow>
      <EuiSpacer size="s" /><EuiButton fill onClick={saveTimezone} isLoading={timezoneBusy} disabled={!timezone || timezone === settings?.timezone}>Save timezone</EuiButton>
    </section>
    {data?.candidate && <section className="section-band">
      <div className="section-heading"><div><EuiTitle size="s"><h2>Staged replacement key</h2></EuiTitle><EuiText color="subdued">Install and verify this public key on every enabled host before activation.</EuiText></div><EuiBadge color="warning">candidate</EuiBadge></div>
      <EuiText size="s"><p><strong>{data.candidate.key_id}</strong> · {data.candidate.algorithm} · {sourceLabel(data.candidate.source)}</p></EuiText>
      <EuiCodeBlock language="text" paddingSize="s" isCopyable={false}>{data.candidate.public_key}</EuiCodeBlock>
      <EuiSpacer size="s" /><div className="form-actions"><EuiButtonEmpty iconType="copyClipboard" onClick={() => copyPublicKey(data.candidate!.public_key)}>Copy candidate public key</EuiButtonEmpty><EuiButton fill iconType="check" onClick={() => setAction('activate')}>Activate verified key</EuiButton></div>
    </section>}
    {action && <EuiOverlayMask><EuiModal onClose={close} initialFocus="[data-autofocus]">
      <EuiModalHeader><EuiModalHeaderTitle>{action === 'generate' ? 'Generate controller key' : action === 'import' ? 'Import controller key' : 'Activate controller key'}</EuiModalHeaderTitle></EuiModalHeader>
      <EuiModalBody>
        <EuiText size="s"><p>{action === 'activate' ? 'Activation changes future controller SSH connections only after every enabled host has verified the candidate public key.' : 'Confirm with the current administrator password. Private key material is encrypted at rest and is never displayed again.'}</p></EuiText>
        {action === 'import' && <><EuiSpacer /><EuiFormRow label="OpenSSH private key" isInvalid={Boolean(error)} error={error}><EuiTextArea value={privateKey} onChange={(event) => setPrivateKey(event.target.value)} rows={8} autoComplete="off" /></EuiFormRow><EuiFormRow label="Import passphrase (optional)"><EuiFieldPassword value={passphrase} onChange={(event) => setPassphrase(event.target.value)} autoComplete="off" /></EuiFormRow></>}
        <EuiSpacer /><EuiFormRow label="Current administrator password" isInvalid={Boolean(error) && action !== 'import'} error={action !== 'import' ? error : undefined}><EuiFieldPassword data-autofocus value={adminPassword} onChange={(event) => setAdminPassword(event.target.value)} autoComplete="current-password" onKeyDown={(event) => { if (event.key === 'Enter') submit(); }} /></EuiFormRow>
      </EuiModalBody>
      <EuiModalFooter><EuiButtonEmpty onClick={close}>Cancel</EuiButtonEmpty><EuiButton fill onClick={submit} isLoading={busy} disabled={!adminPassword || (action === 'import' && !privateKey)}>{action === 'activate' ? 'Activate key' : action === 'import' ? 'Import key' : 'Generate key'}</EuiButton></EuiModalFooter>
    </EuiModal></EuiOverlayMask>}
  </div>;
}
